### ISSUE TITLE
Import failed struggling to find solution

### ISSUE THREAD

**Issue by bLAZYYYY** [cubiq/ComfyUI_FaceAnalysis#26]
Cannot solve this issue:
![image](https://github.com/cubiq/ComfyUI_FaceAnalysis/assets/142758030/af91885a-5a9b-48cb-99c5-346cea721d9d)

Keep getting import failed 

![image](https://github.com/cubiq/ComfyUI_FaceAnalysis/assets/142758030/a56b0491-5115-4bc1-bd7e-eaaf40b3735c)

Ive installed dlib and followed instructions for all the dll files too:

![image](https://github.com/cubiq/ComfyUI_FaceAnalysis/assets/142758030/ceab4dc1-70b4-4e17-af2f-a68df30d0e44)
as you can see all dlib files in here:
![image](https://github.com/cubiq/ComfyUI_FaceAnalysis/assets/142758030/1efcdebb-2a0e-4d0b-a9fd-e23a943247d3)

When i open up ComfyUI i get the following messages in cmd prompt:
`Traceback (most recent call last):
  File "C:\Users\myname\Downloads\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1881, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\myname\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis\__init__.py", line 1, in <module>
    from .faceanalysis import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\myname\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis\faceanalysis.py", line 16, in <module>
    raise Exception("Please install either dlib or insightface to use this node.")
Exception: Please install either dlib or insightface to use this node.

Cannot import C:\Users\myname\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis module for custom nodes: Please install either dlib or insightface to use this node.`

Not sure what im doing wrong its probably something really obvious any help would be appreciated.

**Comment by lhovav** [comment]
Hi, I had this issue too, I followed this repo [](https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#installation) under Troubleshooting follow his steps, after installing insightface, the nodes were visible for me...hope it will help

**Comment by YuanGYao** [comment]
This indicates that you have only installed the extension and not dlib or insightface. you need to install one of these two for the extension to work properly.

**Comment by zslefour** [comment]
我遇到过同样问题，后面应该还有类似如下错误信息：
Cannot import H:\V.0.2.7\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
是numpy版本过高导致，安装低点版本后节点可用：
python_embeded\python.exe -m pip install numpy===1.26.4

**Comment by gregorio500** [comment]
The same issue persists. Dlib is installed proper
