### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by aswordok** [cubiq/ComfyUI_FaceAnalysis#30]
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 803.7325925827026
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:26<00:00,  5.29s/it]
Requested to load AutoencoderKL
Loading 1 new model
D:\+AI\myComfyUI\ComfyUI\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\+AI\myComfyUI\ComfyUI\models\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\+AI\myComfyUI\ComfyUI\models\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\+AI\myComfyUI\ComfyUI\models\insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\+AI\myComfyUI\ComfyUI\models\insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\+AI\myComfyUI\ComfyUI\models\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
!!! Exception during processing!!! 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\+AI\myComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\myComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\myComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\myComfyUI\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis\faceanalysis.py", line 382, in analize
    txt_height = font.getmask("Q").getbbox()[3] + font.getmetrics()[1]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

Prompt executed in 137.20 seconds

**Comment by aswordok** [comment]
pip list | findstr "insightface dlib"
dlib                            19.24.99
insightface                     0.7.3

python -c "import torch;import torchvision;import torchaudio;from torch.backends import cudnn;print('CUDA available:', torch.cuda.is_available());print('CUDA Ver:', torch.version.cuda);print('torch Ver:',torch.__version__);print('where torch:',torch.__file__);print('torchvision Ver:',torchvision.__version__);print('torchaudio Ver:',torchaudio.__version__);print('cuDNN available:',cudnn.is_available());print('cuDNN Ver:', torch.backends.cudnn.version())"
CUDA available: True
CUDA Ver: 12.4
torch Ver: 2.5.0.dev20240711+cu124
where torch: D:\+AI\myComfyUI\ComfyUI\venv\Lib\site-packages\torch\__init__.py
torchvision Ver: 0.20.0.dev20240712+cu124
torchaudio Ver: 2.4.0.dev20240712+cu124
cuDNN available: True
cuDNN Ver: 90100

**Comment by cubiq** [comment]
too little info, when does this happen?
